qca-wifi-host-cmn
/home/oem/drive1/aosp14/kernel/xiaomi/laurel_sprout/drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_service_legacy.c:1320:34: error: a function declaration without a prototype 
is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()
                                 ^
                                  void
1 error generated.
make[4]: *** [/home/oem/drive1/aosp14/kernel/xiaomi/laurel_sprout/scripts/Makefile.build:364: drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_service_legacy.o] Ошибка 1
make[4]: *** Ожидание завершения заданий…
/home/oem/drive1/aosp14/kernel/xiaomi/laurel_sprout/drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/target_if/core/src/target_if_main.c:91:40: error: a function declaration without a prototy
pe is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void